### ISSUE TITLE
Kodi 18.9 crashes on some videos

### ISSUE THREAD

**Issue by filigranen** [Dis90/plugin.video.discoveryplus#42] opened 2021-04-11 12:12 UTC
I have been streaming The Big Bang Theory successfully for a week or so, but today kodi crashed upon starting an episode and keeps crashing everytime I try to play.
Nothing has been updated or changed otherwise since yesterday.

I can play the episodes I have seen before, but the next one in line crashes. And any other episode that I have not previously played.
Tried another show with episodes I haven't watched, "Alla mot alla med filip och fredrik" season 5, and those work (only tested three or four).

I have tried to remove my ~/.kodi dir and start anew, no change.
I first suspected widevine or inputstream or something like that, but viaplay works which uses the same helper addons afaik.. so I'm out of ideas.

Here are a few logs: one working (big bang theory season 11 episode 4, that I have previously played), and one log + crashlog for episode 5.
Nothing apparent in the logs that I can see, no tracebacks or errors written.

Working log (episode 4): https://paste.kodi.tv/wapuzedaza.kodi
Crashing log (episode 5): https://paste.kodi.tv/urebasedag.kodi
Kodi's own crashlog/debuglog: https://paste.kodi.tv/gidezuqepa.kodi

Here's a short clip of the crash: https://youtu.be/rIK61KHdBE8 (the black at the end is OBS not finding the window anymore, not part of the crash... just a loading indicator, then crash.)

Not sure if you can find anything wrong, or if it is part of an another addon, but perhaps you can point me in the right direction.

Btw, I also tried this on Windows, same thing. So not OS related.

**Comment by filigranen** [comment] 2021-04-11 15:26
Hmm, I tried another show, "Grey's Anatomy", and it also crashed..
Not sure if "Alla mot alla med filip och fredrik" is a free show that requires login but does not use widevine,
but I doubt "Grey's Anatomy" is free without subscription.
Perhaps it has to do with widewine/DRM after all in some way.. but, like I said, the viaplay addon (https://github.com/emilsvennesson/kodi-viaplay) works - and it also uses widevine...

**Comment by Dis90** [comment] 2021-04-11 16:10
Can you try with Kodi 19? Episode 4 is "drmEnabled" : false and Episode 5 is "drmEnabled" : true
So episode 5 is widevine protected. Kodi or add-on seems to fail to decrypt video stream. Does live tv work?

> InputStream Adaptive: DecryptSampleData: Decrypt failed with error: 2 and key: C53A9877F32C40A3B663C35CDA0AC26A

**Comment by filigranen** [comment] 2021-04-11 17:24
I need another subscription I think, "not permitted to watch", so cannot test.

Will try Kodi 19 in Windows and run a test in a few hours.

**Comment by filigranen** [comment] 2021-04-11 18:16
Had a few moments to spare.

Same with Matrix on Win 10 64 bit. Log here: https://paste.kodi.tv/hukopuyogo.kodi
As before, ep 4 works, ep 5 doesn't.

**Comment by Dis90** [comment] 2021-04-11 18:28
Maybe stupid question but have you tried to play non working episodes on discovery+ website?

**Comment by filigranen** [comment] 2021-04-11 19:25
Yeah, that works. :-)

Also tried on my Shield, so Android crashes aswell on DRM content.

Is this a widevine issue, or something on your side?

Since you ask what works I assume you cannot reproduce?

**Comment by Dis90** [comment] 2021-04-11 19:43
Probably bug in InputStream Adaptive because googling "InputStream Adaptive: DecryptSampleData: Decrypt failed with error:" results issue page of ISA but can also be add-on related.

Yeah I can't reproduce issue. All channels which are DRM protected works fine here in Finland and haven't found any episodes which are DRM protected.

Can go to website with Chrome and open developer tools then go to network tab and start video which doesn't work on Kodi and search .mpd. Download that file and upload here.

**Comment by filigranen** [comment] 2021-04-11 19:57
Oh. So TBBT is not DRM protected in Finland, but in Sweden? Odd ... also odd that ep 4 isn't, but ep 5 is... I would have understood it if season 10 wasn't but season 11 was.

Here's the manifest for TBBT ep 5. Had to zip it for github to play nice:
[manifest.zip](https://github.com/Dis90/plugin.video.discoveryplus/files/6292654/manifest.zip)

manifest.mpd contents are here as well: https://paste.kodi.tv/ebejadigad

Should I open an issue upstream instead?

**Comment by Dis90** [comment] 2021-04-11 20:12
Yep TBBT season 11 ep 5 is not DRM protected in finnish discovery+. I didn't test other episodes.
Likely bug in InputStream Adaptive but I'm not sure but can you open issue here https://github.com/xbmc/inputstream.adaptive

**Comment by filigranen** [comment] 2021-04-11 20:40
Issue posted. Hopefully they can provide some insight as to why this happens.
Thanks for the help (and great addon)!

**Comment by Dis90** [comment] 2021-04-12 15:41
It is now confirmed that this is bug in InputStream Adaptive but I will keep this issue open until ISA is updated with fix. Thanks @filigranen for reporting this :)

**Comment by filigranen** [comment] 2021-04-12 16:29
And thank you for your insights, especially suggesting to download manifest.mpd, probably what made the bug resolved so easily.

Now I just have to wait for a Leia release, or figure out how to build it myself. :-)

**Comment by Dis90** [comment] 2021-06-02 15:15
Fixed in Kodi 19 version of InputStream Adaptive. As far as I know there's not going to be any new releases of ISA for Kodi 18.

**Closed by Dis90** 2021-06-02 15:15 UTC
